### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by crecom86** [Vicky099/Expense#1]
Hello,

Please can you give an installation guide on how to install this expense manager.

Thanks

**Comment by captnwalker** [comment]
Steps to Deploy Locally
Clone down this repo
Restore dependencies by running yarn install in the root of your local repo
Restore production files by running yarn run build:prod
Start local server by running yarn run dev-server
You are now in development mode on localhost:8080
Deploy to host of your choice: ex.; Heroku
Connect to a database and setup authentication of your choice: ex.; Firebase
Create Firebase DB and authentication per Firebase documentation
Add your API keys to your local project
Set Firebase API keys in Heroku from command line: heroku config:set <list all 6 keys copied from your .env file and separated by a space>
You should now be able to login to your deployed site
